export { default as Navbar } from "./Navbar/Navbar"
export { default as HeaderComponent } from "./Header/HeaderComponent"
export { default as Footer } from "./Footer/Footer"
export { default as CardBox } from "./Cards/CardBox"
export { default as TitlePage } from "./TitleName/TitlePage"
export { default as Services } from "../Sections/Services/Services"
export { default as Difference } from "../Sections/Difference/Difference"
export { default as HomeCarousel } from "../Sections/HomeCarousel/HomeCarousel"
export { default as PageNavbar } from "../Components/PageNavbar/PageNavbar"
export { default as AboutUAE } from "../Routes/About/Pages/AboutUAE/AboutUAE"
export { default as AboutGallery } from "../Routes/About/Pages/AboutGallery/AboutGallery"
export { default as TourExcursionsPage } from "../Routes/TourExcursions/TourExcursionsPage"
export { default as About } from "../Routes/About/About"
export { default as Contact } from "../Routes/Contact/Contact"
export { default as MiceService } from "../Routes/MiceService/MiceService"
export { default as ServicesPage } from "../Routes/ServicePage/ServicesPage"
export { default as Attractions } from "../Routes/TourExcursions/Pages/Attractions/Attractions"
export { default as Sightseeing } from "../Routes/TourExcursions/Pages/Sightseeing/Sightseeing"
export { default as SelfDrive } from "../Routes/TourExcursions/Pages/SelfDrive/SelfDrive"



